import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'
import path from 'path'
import { cpSync, existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

// Target for the same-origin `/rpc` proxy. Defaults to the live seed node for
// local dev / preview, but the e2e suite overrides it (E2E_RPC_PROXY_TARGET) to
// point at a local JSON-RPC mock so the explorer specs are hermetic and do not
// depend on the shared public node being responsive. See web/e2e/serve-rpc-mock.mjs.
const RPC_PROXY_TARGET = process.env.E2E_RPC_PROXY_TARGET || 'https://seed.botho.io'

// Absolute path to the generated @botho/wasm-signer artifact (`pkg/`).
const WASM_PKG_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'wasm-signer',
  'pkg',
)

/**
 * Serve + bundle the client-side signer wasm at `/pkg/`.
 *
 * `@botho/wasm-signer`'s `loadSigner()` instantiates the wasm in the browser via
 * a runtime dynamic import of `../pkg/bth_wasm_signer.js` (with `@vite-ignore`,
 * so Vite does NOT bundle it — the artifact is generated by `wasm-pack`, not
 * source). Once bundled, that resolves to `/pkg/bth_wasm_signer.js` at the site
 * root, and the glue in turn fetches `/pkg/bth_wasm_signer_bg.wasm`. Neither
 * exists unless we publish the `pkg/` directory at `/pkg/`. This plugin:
 *   - dev/preview: answers `/pkg/*` requests straight from the pkg dir, and
 *   - build: copies `pkg/` into `dist/pkg/`,
 * so the real client-side build/sign/submit path works in the browser. No-ops
 * (with a warning) when the artifact is absent so a wasm-less build still runs.
 */
function wasmSignerPkgPlugin(): Plugin {
  const contentType = (p: string) =>
    p.endsWith('.wasm')
      ? 'application/wasm'
      : p.endsWith('.js')
        ? 'text/javascript'
        : 'application/octet-stream'
  const serve: Parameters<NonNullable<Plugin['configureServer']>>[0]['middlewares']['use'] = (
    req: { url?: string },
    res: { setHeader: (k: string, v: string) => void; end: (b?: unknown) => void; statusCode: number },
    next: () => void,
  ) => {
    const url = req.url ?? ''
    if (!url.startsWith('/pkg/')) return next()
    const rel = url.split('?')[0].replace(/^\/pkg\//, '')
    const file = path.join(WASM_PKG_DIR, rel)
    if (!file.startsWith(WASM_PKG_DIR) || !existsSync(file)) return next()
    res.setHeader('Content-Type', contentType(file))
    res.end(readFileSync(file))
  }
  return {
    name: 'botho-wasm-signer-pkg',
    configureServer(server) {
      server.middlewares.use(serve as never)
    },
    configurePreviewServer(server) {
      server.middlewares.use(serve as never)
    },
    closeBundle() {
      if (!existsSync(WASM_PKG_DIR)) {
        this.warn(
          `@botho/wasm-signer pkg not found at ${WASM_PKG_DIR}; the in-browser ` +
            'signer will not load. Build it with `pnpm --filter @botho/wasm-signer build:wasm`.',
        )
        return
      }
      cpSync(WASM_PKG_DIR, path.resolve(__dirname, 'dist', 'pkg'), { recursive: true })
    },
  }
}

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    wasmSignerPkgPlugin(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.svg'],
      manifest: {
        name: 'Botho Wallet',
        short_name: 'Botho',
        description: 'Privacy-first cryptocurrency wallet',
        theme_color: '#06b6d4',
        background_color: '#0a0b0f',
        display: 'standalone',
        orientation: 'portrait',
        scope: '/',
        start_url: '/',
        icons: [
          {
            src: 'pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        navigateFallbackDenylist: [/\.pdf$/],
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'https://seed.botho.io',
        changeOrigin: true,
      },
      // Same-origin proxy to the seed node read RPC. Used during local dev and
      // e2e (build with VITE_RPC_ENDPOINT=/rpc) so the app reaches a real node
      // without depending on cross-origin CORS.
      '/rpc': {
        target: RPC_PROXY_TARGET,
        changeOrigin: true,
      },
    },
  },
  // `vite preview` (used by the e2e webServer) needs the same /rpc proxy as the
  // dev server so the served production build can reach the seed node RPC.
  preview: {
    proxy: {
      '/rpc': {
        target: RPC_PROXY_TARGET,
        changeOrigin: true,
      },
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
})
