import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'
import path from 'path'
import { createHash } from 'node:crypto'
import { cpSync, existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

// Target for the same-origin `/rpc` proxy. Defaults to the live seed node for
// local dev / preview, but the e2e suite overrides it (E2E_RPC_PROXY_TARGET) to
// point at a local JSON-RPC mock so the explorer specs are hermetic and do not
// depend on the shared public node being responsive. See web/e2e/serve-rpc-mock.mjs.
const RPC_PROXY_TARGET = process.env.E2E_RPC_PROXY_TARGET || 'https://seed.botho.io'

// Absolute path to the generated @botho/wasm-signer artifact (`pkg/`).
const WASM_PKG_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'wasm-signer',
  'pkg',
)

/**
 * Serve + bundle the client-side signer wasm at `/pkg/`.
 *
 * `@botho/wasm-signer`'s `loadSigner()` instantiates the wasm in the browser via
 * a runtime dynamic import of `../pkg/bth_wasm_signer.js` (with `@vite-ignore`,
 * so Vite does NOT bundle it — the artifact is generated by `wasm-pack`, not
 * source). Once bundled, that resolves to `/pkg/bth_wasm_signer.js` at the site
 * root, and the glue in turn fetches `/pkg/bth_wasm_signer_bg.wasm`. Neither
 * exists unless we publish the `pkg/` directory at `/pkg/`. This plugin:
 *   - dev/preview: answers `/pkg/*` requests straight from the pkg dir, and
 *   - build: copies `pkg/` into `dist/pkg/`,
 * so the real client-side build/sign/submit path works in the browser. No-ops
 * (with a warning) when the artifact is absent so a wasm-less build still runs.
 */
function wasmSignerPkgPlugin(): Plugin {
  const contentType = (p: string) =>
    p.endsWith('.wasm')
      ? 'application/wasm'
      : p.endsWith('.js')
        ? 'text/javascript'
        : 'application/octet-stream'
  const serve: Parameters<NonNullable<Plugin['configureServer']>>[0]['middlewares']['use'] = (
    req: { url?: string },
    res: { setHeader: (k: string, v: string) => void; end: (b?: unknown) => void; statusCode: number },
    next: () => void,
  ) => {
    const url = req.url ?? ''
    if (!url.startsWith('/pkg/')) return next()
    const rel = url.split('?')[0].replace(/^\/pkg\//, '')
    const file = path.join(WASM_PKG_DIR, rel)
    if (!file.startsWith(WASM_PKG_DIR) || !existsSync(file)) return next()
    res.setHeader('Content-Type', contentType(file))
    res.end(readFileSync(file))
  }
  return {
    name: 'botho-wasm-signer-pkg',
    configureServer(server) {
      server.middlewares.use(serve as never)
    },
    configurePreviewServer(server) {
      server.middlewares.use(serve as never)
    },
    closeBundle() {
      if (!existsSync(WASM_PKG_DIR)) {
        this.warn(
          `@botho/wasm-signer pkg not found at ${WASM_PKG_DIR}; the in-browser ` +
            'signer will not load. Build it with `pnpm --filter @botho/wasm-signer build:wasm`.',
        )
        return
      }
      cpSync(WASM_PKG_DIR, path.resolve(__dirname, 'dist', 'pkg'), { recursive: true })
    },
  }
}

// HTML entry files (relative to the package root) whose emitted document should
// have Subresource Integrity (SRI) hashes injected onto every referenced
// <script>/<link rel="stylesheet"> tag. Only the operator dashboard entry is
// SRI-pinned (#772, §8.3.1 option (a)): its browser-enforced integrity is the
// whole point of splitting it into its own build target. The main SPA entry
// (index.html) is intentionally left unpinned — it is under PWA/auto-update
// service-worker control, where injected integrity hashes on a document the SW
// may replace would be self-defeating.
const SRI_ENTRY_HTML = new Set(['operator.html'])

/**
 * Inject Subresource Integrity (`integrity="sha384-…"` + `crossorigin`) onto the
 * `<script src>` and `<link rel="stylesheet" href>` tags of the operator entry's
 * emitted HTML document (#772, §8.3.1 option (a)).
 *
 * Runs in Rollup's `generateBundle` (build only), after the entry's chunks and
 * CSS have been emitted, so every referenced asset is present in the bundle and
 * its final (hashed) filename is known. For each same-origin, root-relative
 * asset reference in a targeted HTML file we compute the sha384 of the emitted
 * asset's exact bytes and rewrite the tag to pin it. A tampered chunk on the
 * host then fails the browser's integrity check and is never executed — no
 * operator action required.
 *
 * Modeled on the post-build file-manipulation pattern `wasmSignerPkgPlugin`
 * already uses in this file; hand-rolled (no new dependency) for one hash fn.
 */
function sriHashPlugin(): Plugin {
  const sri = (bytes: string | Uint8Array): string =>
    'sha384-' + createHash('sha384').update(bytes).digest('base64')

  return {
    name: 'botho-operator-sri',
    apply: 'build',
    enforce: 'post',
    generateBundle(_options, bundle) {
      // Index emitted assets/chunks by their root-absolute path (`/assets/x.js`)
      // so we can resolve an HTML `src`/`href` to the emitted bytes.
      const byPath = new Map<string, string | Uint8Array>()
      for (const [fileName, output] of Object.entries(bundle)) {
        const bytes =
          output.type === 'chunk'
            ? output.code
            : typeof output.source === 'string'
              ? output.source
              : output.source
        byPath.set('/' + fileName, bytes)
      }

      for (const [fileName, output] of Object.entries(bundle)) {
        if (output.type !== 'asset') continue
        if (!SRI_ENTRY_HTML.has(fileName)) continue
        const html =
          typeof output.source === 'string'
            ? output.source
            : Buffer.from(output.source).toString('utf8')

        // Rewrite <script src="…">, <link rel="stylesheet" href="…"> and
        // <link rel="modulepreload" href="…">, adding integrity (+ crossorigin
        // where absent) for each root-relative asset we can resolve. The browser
        // enforces integrity on all three, including modulepreloaded chunks the
        // operator entry statically imports (e.g. the shared framework chunk).
        const rewritten = html.replace(
          /<(script|link)\b[^>]*>/gi,
          (tag: string) => {
            const isScript = /^<script/i.test(tag)
            const isStyle =
              /^<link/i.test(tag) && /rel\s*=\s*["']stylesheet["']/i.test(tag)
            const isModulePreload =
              /^<link/i.test(tag) && /rel\s*=\s*["']modulepreload["']/i.test(tag)
            if (!isScript && !isStyle && !isModulePreload) return tag
            if (/\bintegrity\s*=/i.test(tag)) return tag // already pinned

            const attr = isScript ? 'src' : 'href'
            const m = tag.match(new RegExp(`\\b${attr}\\s*=\\s*["']([^"']+)["']`, 'i'))
            if (!m) return tag
            const ref = m[1]
            const bytes = byPath.get(ref)
            if (bytes === undefined) return tag // external / unresolved — skip

            const integrity = sri(bytes)
            const closeIdx = tag.lastIndexOf('>')
            const selfClosing = tag[closeIdx - 1] === '/'
            const insertAt = selfClosing ? closeIdx - 1 : closeIdx
            // Vite already emits a bare `crossorigin` on its own tags; only add
            // one when the tag lacks it, to avoid a duplicate attribute.
            const needsCrossorigin = !/\bcrossorigin\b/i.test(tag)
            const injected =
              ` integrity="${integrity}"` +
              (needsCrossorigin ? ' crossorigin="anonymous"' : '')
            return tag.slice(0, insertAt) + injected + tag.slice(insertAt)
          },
        )

        output.source = rewritten
      }
    },
  }
}

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    wasmSignerPkgPlugin(),
    sriHashPlugin(),
    VitePWA({
      registerType: 'autoUpdate',
      // We register the service worker ourselves via the `virtual:pwa-register`
      // module in `src/main.tsx` so we can auto-reload the page once a new SW
      // takes control after a deploy. The default injected registration does
      // NOT reload, leaving users on the stale cached app until a manual hard
      // refresh. Setting this to `null` disables the auto-injected registration
      // so we don't register the SW twice.
      injectRegister: null,
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.svg'],
      manifest: {
        name: 'Botho Wallet',
        short_name: 'Botho',
        description: 'Privacy-first cryptocurrency wallet',
        theme_color: '#06b6d4',
        background_color: '#0a0b0f',
        display: 'standalone',
        orientation: 'portrait',
        scope: '/',
        start_url: '/',
        icons: [
          {
            src: 'pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        // Keep the operator dashboard document out of the precache manifest
        // (#772, §8.3.1 option (a)). The SW must never cache or serve
        // `operator.html`, so the browser always fetches the operator entry
        // fresh over the network — an auto-updated SW then cannot silently swap
        // the top-level document that pins the SRI hashes. The referenced JS/CSS
        // chunks are still integrity-checked by the browser on that fresh fetch.
        globIgnores: ['operator.html'],
        // Never let the SPA's navigation fallback hijack /operator: it must
        // resolve to the standalone operator document, not the main app shell.
        navigateFallbackDenylist: [/\.pdf$/, /^\/operator(\/|$)/, /\/operator\.html$/],
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'https://seed.botho.io',
        changeOrigin: true,
      },
      // Same-origin proxy to the seed node read RPC. Used during local dev and
      // e2e (build with VITE_RPC_ENDPOINT=/rpc) so the app reaches a real node
      // without depending on cross-origin CORS.
      '/rpc': {
        target: RPC_PROXY_TARGET,
        changeOrigin: true,
      },
    },
  },
  // `vite preview` (used by the e2e webServer) needs the same /rpc proxy as the
  // dev server so the served production build can reach the seed node RPC.
  preview: {
    proxy: {
      '/rpc': {
        target: RPC_PROXY_TARGET,
        changeOrigin: true,
      },
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
    rollupOptions: {
      // Multi-page build (#772, §8.3.1 option (a)): the main SPA (index.html)
      // and the standalone operator dashboard (operator.html) are two entry
      // documents in the same Cloudflare Pages project. Vite emits a distinct
      // entry chunk graph per entry; the operator document references only its
      // own chunks, which `sriHashPlugin` then integrity-pins.
      input: {
        main: path.resolve(__dirname, 'index.html'),
        operator: path.resolve(__dirname, 'operator.html'),
      },
    },
  },
})
