// Copyright (c) 2018-2022 The Botho Foundation

//! Botho gRPC API.

mod autogenerated_code {
    // Include the auto-generated code.
    // Note: external and blockchain types use extern_path to ::bt_api
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}

// Re-export bt_api types for compatibility
pub use bt_api::{blockchain, external};

pub mod conversions;

pub use autogenerated_code::*;
pub use bt_api::ConversionError;
