// Copyright (c) 2018-2022 The Botho Foundation

//! Botho gRPC API.

mod autogenerated_code {
    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}
mod convert;

pub mod display;

pub use crate::{autogenerated_code::*, convert::*};
