#!/bin/bash
# Use this file to prevent accidental pushes to protected branches
# Based on https://gist.githubusercontent.com/stefansundin/d465f1e331fc5c632088/raw/pre-push-2
#
# This is not installed by install_git_settings.sh.
# To turn this on, use a similar command
# as the one there that creates a symlink in .git/hooks
#
# It may require manual configuration depending on how you have configured your remotes
# https://git-scm.com/docs/githooks#_pre_push

exit 0
