//! CT-compatible lottery-selection sweep — the design-research gate for the
//! lottery sub-problem of issue #902 (confidential amounts × value-dependent
//! economics).
//!
//! # The problem this sweep exists to answer
//!
//! The redistribution lottery (`cluster-tax/src/lottery.rs`,
//! `botho/src/consensus/lottery.rs`) draws winners with weight
//!
//! ```text
//! weight = value × (max_factor − factor + 1)      // SelectionMode::ClusterWeighted
//! ```
//!
//! This is the incumbent default and the *only* split-invariant progressive
//! mode: because the weight is **linear in the UTXO value**, splitting a
//! position into many outputs never changes the total weight, while the
//! `(max_factor − factor + 1)` tilt keys off cluster provenance (which inherits
//! through splits). See `docs/design/cluster-tilted-redistribution.md`.
//!
//! Under **confidential amounts** (ADR 0006 decision 1) the UTXO `value` is
//! hidden. Reading it in a consensus weight forces a **ZK weighted-sampling
//! proof over hidden values** (a Merkle-sum tree / proof-of-liabilities sort;
//! see #902 §3). That is the single hardest gadget in the CT epic.
//!
//! # The value-free reframe under test
//!
//! The maintainer's insight: the lottery is only hard under CT because the
//! selection rule reads the hidden value. A **value-free** rule keyed only on
//! signals that stay **public even under CT** needs no proof over amounts:
//!
//! - the transaction **fee** (public by ADR 0006), and under demurrage `fee ≈
//!   base + value × factor × rate × time_held` — a monotone proxy for `value ×
//!   factor`;
//! - coin **circulation** (has it been spent-and-recreated recently — public
//!   from creation heights);
//! - cluster **factor/tag** structure (public chain state).
//!
//! This module scores five selection rules head-to-head on the three axes #902
//! cares about — **redistribution** (Δgini vs a burn baseline), **Sybil
//! resistance** (weight gain when a whale splits a position), and
//! **CT-compatibility / leakage** — to determine whether any value-free rule
//! *recovers* ClusterWeighted's redistribution while staying Sybil-resistant
//! and CT-clean, or whether the ZK-sort is unavoidable.
//!
//! # Method (a focused, deterministic Monte-Carlo)
//!
//! Same shape as the shipped [`super::settlement_horizon_sweep`] and
//! [`super::decoy_quantile_sweep`]: a focused deterministic experiment, not the
//! full agent framework, because the lever here is the *selection rule*, not
//! multi-agent transaction flow. It reuses the shipped consensus kernels — the
//! real [`crate::demurrage_charge`] (to compute the public-fee proxy), the real
//! [`crate::ClusterFactorCurve`] (to derive factor classes from cluster
//! wealth), the real [`crate::LotteryCandidate`]/[`crate::SelectionMode`]
//! weights for the Uniform and ClusterWeighted yardsticks (NO second
//! implementation of the incumbent), and the shared
//! [`super::metrics::calculate_gini`]. All numbers in `docs/research/
//! ct-compatible-lottery-selection.md` are regenerated by this module — nothing
//! is hand-computed. The redistribution track uses expected-value weighting
//! (deterministic, no RNG noise), so the output is byte-for-byte reproducible.

use crate::{
    demurrage_charge, fee_curve::PICO_PER_BTH, ClusterFactorCurve, LotteryCandidate, SelectionMode,
    TagVector,
};

use super::metrics::calculate_gini;

/// Blocks per year at the 5s reference block time (matches the node and the
/// other sweeps).
pub const BLOCKS_PER_YEAR: u64 = 6_307_200;

/// Annual demurrage rate at maximum factor, basis points (2%/yr, #351).
pub const RATE_BPS: u32 = 200;

/// Public per-output base fee floor, in picocredits (0.25 BTH). Every output a
/// transaction creates pays at least this. It is the ONLY real cost a splitter
/// pays per extra ticket, so it is the sole brake on a fee-keyed value-free
/// rule — quantified in the Sybil table.
pub const BASE_FEE_PICO: u128 = PICO_PER_BTH / 4;

/// Circulation weight boost for the value-free `CirculationGated` rule: a coin
/// that has recently been spent-and-recreated (commerce, low idle age) gets
/// this multiplier over an idle hoarded coin.
pub const CIRCULATION_BOOST: u128 = 10;

/// Deterministic seed (kept for structural parity with the other sweeps; the
/// redistribution track is expected-value and needs no draws, but the constant
/// documents the run's identity and lets future stochastic variants hang off
/// it).
pub const SEED: u64 = 0xB07A_0902;

/// A selection rule under test.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Rule {
    /// Every eligible UTXO has equal weight. Value-free, CT-clean. The "rely on
    /// statistics" null baseline. Sybil resistance is poor (splitting =
    /// tickets).
    Uniform,
    /// Incumbent `value × (max_factor − factor + 1)`. Split-invariant and
    /// progressive, but reads the hidden value → NOT CT-compatible. Included
    /// only as the redistribution yardstick.
    ClusterWeighted,
    /// Value-free: weight ∝ `(max_fee − fee + 1)`. Low public fee (poor /
    /// low-factor / freshly circulated) → more weight. Reads only the public
    /// fee, so CT-clean.
    FeeInverse,
    /// Value-free: a coin that has circulated recently gets
    /// `CIRCULATION_BOOST`× weight, an idle hoarded coin gets 1×. Reads
    /// only public creation age → CT-clean.
    CirculationGated,
    /// Value-free hybrid: `FeeInverse × circulation boost`. CT-clean.
    Hybrid,
}

impl Rule {
    /// All rules in report order.
    pub fn all() -> Vec<Rule> {
        vec![
            Rule::Uniform,
            Rule::ClusterWeighted,
            Rule::FeeInverse,
            Rule::CirculationGated,
            Rule::Hybrid,
        ]
    }

    /// Human label.
    pub fn label(self) -> &'static str {
        match self {
            Rule::Uniform => "Uniform",
            Rule::ClusterWeighted => "ClusterWeighted",
            Rule::FeeInverse => "FeeInverse",
            Rule::CirculationGated => "CirculationGated",
            Rule::Hybrid => "Hybrid(fee×circ)",
        }
    }

    /// Does the rule read the hidden UTXO value? If so it is NOT CT-compatible.
    pub fn reads_hidden_value(self) -> bool {
        matches!(self, Rule::ClusterWeighted)
    }

    /// CT-compatible iff it never reads the hidden value (keys only on the
    /// public fee, public age/circulation, or nothing).
    pub fn is_ct_clean(self) -> bool {
        !self.reads_hidden_value()
    }

    /// One-line justification of the CT-compatibility verdict.
    pub fn ct_reason(self) -> &'static str {
        match self {
            Rule::Uniform => "reads nothing about value (equal weight)",
            Rule::ClusterWeighted => "weight ∝ hidden value → needs a ZK sort over amounts",
            Rule::FeeInverse => "reads only the public fee (already public under ADR 0006)",
            Rule::CirculationGated => "reads only public creation age / circulation",
            Rule::Hybrid => "reads only public fee + public age",
        }
    }

    /// Incremental metadata leakage beyond what ADR 0006 already makes public.
    pub fn leakage(self) -> &'static str {
        match self {
            Rule::Uniform => "none",
            Rule::ClusterWeighted => "N/A (not CT-compatible)",
            // The fee is already public by design, so keying on it adds nothing
            // the §9 metadata table does not already account for.
            Rule::FeeInverse => "none beyond the already-public fee",
            Rule::CirculationGated => "none (creation heights already public)",
            Rule::Hybrid => "none beyond the already-public fee + age",
        }
    }
}

/// A holder / UTXO in the population.
#[derive(Clone, Copy, Debug)]
pub struct Holder {
    /// On-chain wealth in picocredits (the hidden value under CT).
    pub wealth_pico: u128,
    /// Cluster factor in FACTOR_SCALE units (1000..=6000), from the real curve.
    pub factor_scaled: u64,
    /// Has this coin circulated recently (spent-and-recreated / commerce)?
    /// Value-free public signal.
    pub circulated: bool,
}

/// The public fee proxy for a holding, in picocredits:
/// `base_fee + demurrage_owed(value, factor, elapsed)`. This is the CT-public
/// signal a value-free rule keys on. `elapsed_blocks` is the coin's public idle
/// age (a freshly circulated coin has a small elapsed → a fee near the base
/// floor).
pub fn public_fee_pico(wealth_pico: u128, factor_scaled: u64, elapsed_blocks: u64) -> u128 {
    // demurrage_charge takes a u64 value in base units; coin values here are
    // <= tens of millions of BTH (< u64::MAX picocredits), so the cast is safe.
    let value_u64 = u64::try_from(wealth_pico).unwrap_or(u64::MAX);
    let dem = demurrage_charge(
        value_u64,
        factor_scaled,
        elapsed_blocks,
        RATE_BPS,
        BLOCKS_PER_YEAR,
    ) as u128;
    BASE_FEE_PICO + dem
}

/// Compute the selection weight for one holder under a rule.
///
/// - `value_bth` — the holder's value in whole BTH (the ClusterWeighted /
///   Uniform yardsticks are computed via the REAL [`LotteryCandidate::weight`]
///   at BTH scale to avoid any second implementation of the incumbent).
/// - `max_value_bth` — population max value in BTH (Hybrid normalization input
///   to the kernel; unused by the modes we call but kept for fidelity).
/// - `fee_pico`, `max_fee_pico` — the public fee proxy and its population max.
pub fn weight(
    rule: Rule,
    value_bth: u64,
    factor_scaled: u64,
    max_value_bth: u64,
    fee_pico: u128,
    max_fee_pico: u128,
    circulated: bool,
) -> u128 {
    match rule {
        // Yardsticks: use the REAL consensus kernel weights, not a re-derivation.
        Rule::Uniform => real_kernel_weight(
            SelectionMode::Uniform,
            value_bth,
            factor_scaled,
            max_value_bth,
        ),
        Rule::ClusterWeighted => real_kernel_weight(
            SelectionMode::ClusterWeighted,
            value_bth,
            factor_scaled,
            max_value_bth,
        ),
        // Value-free: low public fee → more weight. `+1` avoids a zero weight
        // for the single max-fee coin.
        Rule::FeeInverse => max_fee_pico.saturating_sub(fee_pico) + 1,
        // Value-free: circulated coins get the boost, idle coins get 1.
        Rule::CirculationGated => {
            if circulated {
                CIRCULATION_BOOST
            } else {
                1
            }
        }
        // Value-free compound.
        Rule::Hybrid => {
            let fee_term = max_fee_pico.saturating_sub(fee_pico) + 1;
            let circ = if circulated { CIRCULATION_BOOST } else { 1 };
            fee_term.saturating_mul(circ)
        }
    }
}

/// The incumbent weights via the shipped [`LotteryCandidate::weight`] — this is
/// the reuse contract: the Uniform and ClusterWeighted columns are the exact
/// consensus numbers, not a copy.
fn real_kernel_weight(
    mode: SelectionMode,
    value_bth: u64,
    factor_scaled: u64,
    max_value_bth: u64,
) -> u128 {
    let candidate =
        LotteryCandidate::new([0u8; 36], value_bth, factor_scaled, &TagVector::new(), 0);
    candidate.weight(mode, max_value_bth.max(1))
}

// ===========================================================================
// Track 1 — redistribution (Δgini vs a burn baseline)
// ===========================================================================

/// One population tier for the redistribution experiment.
#[derive(Clone, Copy, Debug)]
pub struct Tier {
    pub label: &'static str,
    pub count: usize,
    pub wealth_bth: u64,
    pub cluster_wealth_bth: u64,
    pub circulated: bool,
}

/// The redistribution population: a large poor/background tier (factor 1,
/// circulated commerce coins) plus a graded wealthy tier spanning the real
/// factor curve (idle hoarders). Factors are derived from the REAL
/// [`ClusterFactorCurve`] at each tier's cluster wealth.
pub fn population_tiers() -> Vec<Tier> {
    vec![
        Tier {
            label: "background (poor)",
            count: 90,
            wealth_bth: 1_000,
            cluster_wealth_bth: 1_000,
            circulated: true,
        },
        // Graded wealthy tier — a factor gradient so FeeInverse (∝ 1/fee) and
        // ClusterWeighted (∝ value·(maxf−f)) are genuinely different functions.
        Tier {
            label: "50k-cluster wealthy",
            count: 4,
            wealth_bth: 5_000,
            cluster_wealth_bth: 50_000,
            circulated: false,
        },
        Tier {
            label: "500k-cluster wealthy",
            count: 3,
            wealth_bth: 50_000,
            cluster_wealth_bth: 500_000,
            circulated: false,
        },
        Tier {
            label: "10M-cluster whale",
            count: 3,
            wealth_bth: 100_000,
            cluster_wealth_bth: 10_000_000,
            circulated: false,
        },
    ]
}

/// Build the flat holder vector from the tiers.
pub fn build_population(tiers: &[Tier]) -> Vec<Holder> {
    let curve = ClusterFactorCurve::default_params();
    let mut holders = Vec::new();
    for t in tiers {
        let factor = curve.factor(t.cluster_wealth_bth as u128 * PICO_PER_BTH);
        for _ in 0..t.count {
            holders.push(Holder {
                wealth_pico: t.wealth_bth as u128 * PICO_PER_BTH,
                factor_scaled: factor,
                circulated: t.circulated,
            });
        }
    }
    holders
}

/// Result of the redistribution experiment for one rule.
#[derive(Clone, Debug)]
pub struct RedistRow {
    pub rule: Rule,
    /// Final Gini after `years` of collect-and-redistribute under this rule.
    pub final_gini: f64,
    /// Δgini = burn_baseline_gini − final_gini (positive = more equalizing).
    pub delta_gini: f64,
    /// Recovery vs ClusterWeighted: delta_gini / delta_gini(ClusterWeighted).
    pub recovery_pct: f64,
    pub ct_clean: bool,
}

/// Run the collect-and-redistribute loop for one rule and return the final
/// Gini.
///
/// Each round: every wealthy holder pays one year of ordinary demurrage into a
/// pool (factor-1 poor pay zero); the pool is then redistributed by the rule's
/// weights (expected value: holder `i` receives `pool × w_i / Σw`). A `burn`
/// world collects the same demurrage but does not redistribute (the Δgini
/// anchor).
fn run_redistribution(holders: &[Holder], years: u64, rule: Option<Rule>) -> f64 {
    let mut wealth: Vec<u128> = holders.iter().map(|h| h.wealth_pico).collect();
    let factor: Vec<u64> = holders.iter().map(|h| h.factor_scaled).collect();
    let circulated: Vec<bool> = holders.iter().map(|h| h.circulated).collect();
    let mut carry: u128 = 0;

    for _ in 0..years {
        // --- Collect one year of demurrage from every holder.
        let mut pool: u128 = carry;
        for i in 0..wealth.len() {
            let value_u64 = u64::try_from(wealth[i]).unwrap_or(u64::MAX);
            let charge = demurrage_charge(
                value_u64,
                factor[i],
                BLOCKS_PER_YEAR,
                RATE_BPS,
                BLOCKS_PER_YEAR,
            ) as u128;
            let charge = charge.min(wealth[i]);
            wealth[i] -= charge;
            pool += charge;
        }

        // --- Redistribute (or burn if rule is None).
        let Some(rule) = rule else {
            // Burn baseline: pool leaves the system; nothing is paid out.
            carry = 0;
            continue;
        };

        // Current-round public-fee proxy + max value, recomputed from live
        // wealth (a coin's fee tracks its current value·factor).
        let max_value_bth = wealth
            .iter()
            .map(|w| (w / PICO_PER_BTH) as u64)
            .max()
            .unwrap_or(1);
        let fees: Vec<u128> = (0..wealth.len())
            .map(|i| {
                // Idle wealthy coins carry a full year of accrued demurrage in
                // their fee; circulated coins are fresh (elapsed ~ 0), so their
                // fee sits at the base floor.
                let elapsed = if circulated[i] { 0 } else { BLOCKS_PER_YEAR };
                public_fee_pico(wealth[i], factor[i], elapsed)
            })
            .collect();
        let max_fee = fees.iter().copied().max().unwrap_or(1);

        let weights: Vec<u128> = (0..wealth.len())
            .map(|i| {
                let value_bth = (wealth[i] / PICO_PER_BTH) as u64;
                weight(
                    rule,
                    value_bth,
                    factor[i],
                    max_value_bth,
                    fees[i],
                    max_fee,
                    circulated[i],
                )
            })
            .collect();
        let total_weight: u128 = weights.iter().sum();

        if total_weight == 0 {
            carry = pool;
            continue;
        }

        // Expected-value payout: holder i receives pool × w_i / Σw. Integer
        // division; the indivisible remainder carries to the next round.
        let mut distributed: u128 = 0;
        for i in 0..wealth.len() {
            let share = pool.saturating_mul(weights[i]) / total_weight;
            wealth[i] += share;
            distributed += share;
        }
        carry = pool - distributed;
    }

    // Gini over BTH-scaled wealth (ratio-invariant; keeps values in u64).
    let final_wealths: Vec<u64> = wealth
        .iter()
        .map(|&w| u64::try_from(w / PICO_PER_BTH).unwrap_or(u64::MAX))
        .collect();
    calculate_gini(&final_wealths)
}

/// Run the redistribution track for all rules.
pub fn redistribution_sweep(holders: &[Holder], years: u64) -> Vec<RedistRow> {
    let burn_gini = run_redistribution(holders, years, None);
    // ClusterWeighted is the recovery yardstick.
    let cw_gini = run_redistribution(holders, years, Some(Rule::ClusterWeighted));
    let cw_delta = (burn_gini - cw_gini).max(1e-12);

    Rule::all()
        .into_iter()
        .map(|rule| {
            let final_gini = run_redistribution(holders, years, Some(rule));
            let delta_gini = burn_gini - final_gini;
            RedistRow {
                rule,
                final_gini,
                delta_gini,
                recovery_pct: delta_gini / cw_delta * 100.0,
                ct_clean: rule.is_ct_clean(),
            }
        })
        .collect()
}

// ===========================================================================
// Track 2 — Sybil resistance (weight gain under splitting)
// ===========================================================================

/// One row of the splitting-attack table for a rule at a split count.
///
/// The metric is the attacker's **share of total lottery weight** in a fixed
/// reference population (all others' weights held constant), unsplit vs split.
/// This is bounded in `[0, 1]` (a splitter can never exceed 100% of the
/// tickets), so it is both interpretable and captures the natural self-limit —
/// the more the attacker splits, the more the denominator grows. `share_gain`
/// is `share_split / share_unsplit`.
#[derive(Clone, Debug)]
pub struct SybilRow {
    pub rule: Rule,
    pub split_k: u32,
    /// Attacker ticket share when holding one unsplit coin.
    pub share_unsplit: f64,
    /// Attacker ticket share after fragmenting into `split_k` fresh coins.
    pub share_split: f64,
    /// share_split / share_unsplit (1.0 = split-invariant; grows toward the
    /// share cap for per-ticket rules).
    pub share_gain: f64,
    pub ct_clean: bool,
}

/// The attacker: a single saturated-whale coin (10M-BTH cluster, factor
/// ~5.745), value 100k BTH, held idle for one year. It fragments into `k` equal
/// coins.
#[derive(Clone, Copy, Debug)]
pub struct SybilAttacker {
    pub value_bth: u64,
    pub factor_scaled: u64,
}

/// Build the default attacker from the real curve.
pub fn default_attacker() -> SybilAttacker {
    let curve = ClusterFactorCurve::default_params();
    let factor = curve.factor(10_000_000u128 * PICO_PER_BTH);
    SybilAttacker {
        value_bth: 100_000,
        factor_scaled: factor,
    }
}

/// Split counts swept.
pub fn split_counts() -> Vec<u32> {
    vec![10, 100, 1_000]
}

/// The reference population the attacker's ticket share is measured against:
/// the redistribution population (which already contains idle 10M-whales, so
/// the population `max_fee` stays high even after the attacker's own coins
/// fragment to the base floor — the realistic case).
fn reference_population() -> Vec<Holder> {
    build_population(&population_tiers())
}

/// Compute the (unsplit_weights, max_value_bth, max_fee_pico) for the reference
/// population plus the attacker's coins. `attacker_coins` are appended so the
/// population maxima account for the attacker.
fn population_weights(rule: Rule, base: &[Holder], attacker_coins: &[Holder]) -> (u128, u128) {
    // (attacker_weight_total, everyone_weight_total)
    let all: Vec<Holder> = base.iter().chain(attacker_coins.iter()).copied().collect();
    let max_value_bth = all
        .iter()
        .map(|h| (h.wealth_pico / PICO_PER_BTH) as u64)
        .max()
        .unwrap_or(1);
    let fees: Vec<u128> = all
        .iter()
        .map(|h| {
            let elapsed = if h.circulated { 0 } else { BLOCKS_PER_YEAR };
            public_fee_pico(h.wealth_pico, h.factor_scaled, elapsed)
        })
        .collect();
    let max_fee = fees.iter().copied().max().unwrap_or(1);

    let mut attacker_w: u128 = 0;
    let mut total_w: u128 = 0;
    for (i, h) in all.iter().enumerate() {
        let value_bth = (h.wealth_pico / PICO_PER_BTH) as u64;
        let w = weight(
            rule,
            value_bth,
            h.factor_scaled,
            max_value_bth,
            fees[i],
            max_fee,
            h.circulated,
        );
        total_w += w;
        if i >= base.len() {
            attacker_w += w;
        }
    }
    (attacker_w, total_w)
}

/// Attacker ticket share for one rule when the whale is split into `k` coins.
pub fn attacker_share(attacker: &SybilAttacker, rule: Rule, k: u32) -> f64 {
    let base = reference_population();
    let piece_value_bth = attacker.value_bth / k as u64;
    // The k fresh split coins (circulated = true, elapsed ≈ 0 → base-floor fee).
    let coins: Vec<Holder> = (0..k)
        .map(|_| Holder {
            wealth_pico: piece_value_bth as u128 * PICO_PER_BTH,
            factor_scaled: attacker.factor_scaled,
            circulated: true,
        })
        .collect();
    let (attacker_w, total_w) = population_weights(rule, &base, &coins);
    if total_w == 0 {
        return 0.0;
    }
    attacker_w as f64 / total_w as f64
}

/// The attacker's unsplit baseline share: a single aged idle whale coin.
fn attacker_share_unsplit(attacker: &SybilAttacker, rule: Rule) -> f64 {
    let base = reference_population();
    let coin = [Holder {
        wealth_pico: attacker.value_bth as u128 * PICO_PER_BTH,
        factor_scaled: attacker.factor_scaled,
        circulated: false, // aged, idle
    }];
    let (attacker_w, total_w) = population_weights(rule, &base, &coin);
    if total_w == 0 {
        return 0.0;
    }
    attacker_w as f64 / total_w as f64
}

/// Run the Sybil track for all rules × split counts.
pub fn sybil_sweep(attacker: &SybilAttacker) -> Vec<SybilRow> {
    let mut rows = Vec::new();
    for rule in Rule::all() {
        let share_unsplit = attacker_share_unsplit(attacker, rule);
        for k in split_counts() {
            let share_split = attacker_share(attacker, rule, k);
            rows.push(SybilRow {
                rule,
                split_k: k,
                share_unsplit,
                share_split,
                share_gain: if share_unsplit > 0.0 {
                    share_split / share_unsplit
                } else {
                    f64::INFINITY
                },
                ct_clean: rule.is_ct_clean(),
            });
        }
    }
    rows
}

/// The extra public fee (in BTH) a splitter pays to fragment into `k` outputs:
/// `(k − 1) × base_fee`. This is the ONLY brake on a fee-keyed value-free rule
/// — the demurrage portion is churn-invariant (conserved), so splitting adds
/// only the per-output base floor.
pub fn split_fee_cost_bth(k: u32) -> f64 {
    (k.saturating_sub(1)) as f64 * (BASE_FEE_PICO as f64 / PICO_PER_BTH as f64)
}

// ===========================================================================
// Report
// ===========================================================================

/// The full sweep report.
#[derive(Clone, Debug)]
pub struct LotterySelectionReport {
    pub tiers: Vec<Tier>,
    pub years: u64,
    pub burn_gini: f64,
    pub initial_gini: f64,
    pub redist_rows: Vec<RedistRow>,
    pub attacker: SybilAttacker,
    pub sybil_rows: Vec<SybilRow>,
}

/// Run the complete lottery-selection sweep with the default configuration.
pub fn run_lottery_selection_sweep() -> LotterySelectionReport {
    let tiers = population_tiers();
    let holders = build_population(&tiers);
    let years = 10;

    let initial: Vec<u64> = holders
        .iter()
        .map(|h| (h.wealth_pico / PICO_PER_BTH) as u64)
        .collect();
    let initial_gini = calculate_gini(&initial);
    let burn_gini = run_redistribution(&holders, years, None);
    let redist_rows = redistribution_sweep(&holders, years);

    let attacker = default_attacker();
    let sybil_rows = sybil_sweep(&attacker);

    LotterySelectionReport {
        tiers,
        years,
        burn_gini,
        initial_gini,
        redist_rows,
        attacker,
        sybil_rows,
    }
}

/// Render the report as Markdown tables (the doc numbers are generated here,
/// never hand-computed).
pub fn to_markdown(report: &LotterySelectionReport) -> String {
    let mut s = String::new();
    let f_scale = ClusterFactorCurve::FACTOR_SCALE as f64;

    // --- Population.
    s.push_str("### Redistribution population (factors from the real `ClusterFactorCurve`)\n\n");
    s.push_str("| tier | count | wealth (BTH) | cluster wealth (BTH) | factor | circulated |\n");
    s.push_str("|------|------:|-------------:|---------------------:|-------:|:----------:|\n");
    let curve = ClusterFactorCurve::default_params();
    for t in &report.tiers {
        let factor = curve.factor(t.cluster_wealth_bth as u128 * PICO_PER_BTH);
        s.push_str(&format!(
            "| {} | {} | {} | {} | {:.3}x | {} |\n",
            t.label,
            t.count,
            t.wealth_bth,
            t.cluster_wealth_bth,
            factor as f64 / f_scale,
            if t.circulated { "yes" } else { "no" },
        ));
    }
    s.push('\n');

    // --- Redistribution table.
    s.push_str("### Track 1 — redistribution (Δgini vs a burn baseline)\n\n");
    s.push_str(&format!(
        "Collect-and-redistribute over {} years. Initial Gini {:.4}; burn baseline \
         (collect demurrage, redistribute nothing) Gini {:.4}. Δgini = burn − rule \
         (higher = more equalizing). Recovery = Δgini ÷ ClusterWeighted's Δgini.\n\n",
        report.years, report.initial_gini, report.burn_gini,
    ));
    s.push_str("| rule | final Gini | Δgini | recovery vs CW | CT-clean |\n");
    s.push_str("|------|-----------:|------:|---------------:|:--------:|\n");
    for r in &report.redist_rows {
        s.push_str(&format!(
            "| {} | {:.4} | {:+.4} | {:.1}% | {} |\n",
            r.rule.label(),
            r.final_gini,
            r.delta_gini,
            r.recovery_pct,
            if r.ct_clean { "yes" } else { "**no**" },
        ));
    }
    s.push('\n');

    // --- Sybil table.
    s.push_str("### Track 2 — Sybil resistance (ticket share under splitting)\n\n");
    let unsplit_share = |rule: Rule| {
        report
            .sybil_rows
            .iter()
            .find(|r| r.rule == rule)
            .map(|r| r.share_unsplit)
            .unwrap_or(f64::NAN)
    };
    s.push_str(&format!(
        "Attacker: one {}-BTH whale coin at factor {:.3}x, fragmented into K fresh equal \
         coins, measured against a fixed reference population of {} holders (which still \
         contains idle whales, so the population max-fee stays high). The metric is the \
         attacker's **share of total lottery weight** (bounded in [0,1] — a splitter can \
         never exceed 100% of tickets). Split-invariant = the share barely moves under a \
         1000-way split (the ClusterWeighted property). The demurrage the whale sheds is \
         churn-invariant, so the only real cost of the split is (K−1)×base_fee = {:.1} BTH \
         at K=1000.\n\n",
        report.attacker.value_bth,
        report.attacker.factor_scaled as f64 / f_scale,
        reference_population().len(),
        split_fee_cost_bth(1_000),
    ));
    s.push_str("| rule | unsplit share | share @K=1000 | split-invariant | CT-clean |\n");
    s.push_str("|------|--------------:|--------------:|:---------------:|:--------:|\n");
    for rule in Rule::all() {
        let row = report
            .sybil_rows
            .iter()
            .find(|r| r.rule == rule && r.split_k == 1_000)
            .unwrap();
        // Split-invariant iff the attacker's ticket share barely moves under a
        // 1000-way split (the ClusterWeighted property).
        let unsplit = unsplit_share(rule);
        let invariant = (row.share_split - unsplit).abs() <= 0.02_f64.max(unsplit * 0.05);
        s.push_str(&format!(
            "| {} | {:.3}% | {:.3}% | {} | {} |\n",
            rule.label(),
            unsplit * 100.0,
            row.share_split * 100.0,
            if invariant { "yes" } else { "**no**" },
            if rule.is_ct_clean() { "yes" } else { "**no**" },
        ));
    }
    s.push('\n');
    // Per-K share progression for the transparency of the self-limit.
    s.push_str("Ticket share by split count K (shows the [0,1] self-limit saturating):\n\n");
    s.push_str("| rule | K=10 | K=100 | K=1000 |\n");
    s.push_str("|------|-----:|------:|-------:|\n");
    for rule in Rule::all() {
        let share = |k: u32| {
            report
                .sybil_rows
                .iter()
                .find(|r| r.rule == rule && r.split_k == k)
                .map(|r| r.share_split * 100.0)
                .unwrap_or(f64::NAN)
        };
        s.push_str(&format!(
            "| {} | {:.3}% | {:.3}% | {:.3}% |\n",
            rule.label(),
            share(10),
            share(100),
            share(1_000),
        ));
    }
    s.push('\n');

    // --- CT-compatibility / leakage summary.
    s.push_str("### CT-compatibility & incremental leakage\n\n");
    s.push_str("| rule | CT-clean | reason | leakage beyond ADR-0006-public |\n");
    s.push_str("|------|:--------:|--------|--------------------------------|\n");
    for rule in Rule::all() {
        s.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            rule.label(),
            if rule.is_ct_clean() { "yes" } else { "**no**" },
            rule.ct_reason(),
            rule.leakage(),
        ));
    }
    s.push('\n');

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cluster_weighted_is_split_invariant() {
        // The defining property: value-linear weight ⇒ splitting never changes
        // the attacker's ticket share. This is why ClusterWeighted is the
        // incumbent — and why it must read the value.
        let attacker = default_attacker();
        let unsplit = attacker_share_unsplit(&attacker, Rule::ClusterWeighted);
        for k in split_counts() {
            let split = attacker_share(&attacker, Rule::ClusterWeighted, k);
            assert!(
                (split - unsplit).abs() / unsplit < 0.02,
                "ClusterWeighted must be ~split-invariant: unsplit {unsplit}, split {split} at K={k}"
            );
        }
    }

    #[test]
    fn value_free_rules_are_sybil_vulnerable() {
        // Every CT-clean value-free rule reintroduces the per-ticket subsidy:
        // splitting materially increases the attacker's ticket share (the
        // property ClusterWeighted was chosen to avoid). Core negative result.
        let attacker = default_attacker();
        for rule in [
            Rule::Uniform,
            Rule::FeeInverse,
            Rule::CirculationGated,
            Rule::Hybrid,
        ] {
            let unsplit = attacker_share_unsplit(&attacker, rule);
            let split = attacker_share(&attacker, rule, 1_000);
            assert!(
                split > unsplit * 2.0,
                "{} should be Sybil-vulnerable (share grows under splitting): unsplit {unsplit}, split {split}",
                rule.label()
            );
        }
    }

    #[test]
    fn yardstick_weights_match_the_real_kernel() {
        // Reuse contract: the Uniform and ClusterWeighted columns are the exact
        // LotteryCandidate::weight numbers, not a re-derivation.
        let value_bth = 50_000u64;
        let factor = 4_000u64;
        let max_value = 100_000u64;
        let cand = LotteryCandidate::new([0u8; 36], value_bth, factor, &TagVector::new(), 0);
        assert_eq!(
            weight(Rule::Uniform, value_bth, factor, max_value, 0, 0, false),
            cand.weight(SelectionMode::Uniform, max_value)
        );
        assert_eq!(
            weight(
                Rule::ClusterWeighted,
                value_bth,
                factor,
                max_value,
                0,
                0,
                false
            ),
            cand.weight(SelectionMode::ClusterWeighted, max_value)
        );
    }

    #[test]
    fn feeinverse_recovers_most_redistribution() {
        // The positive half of the result: the best value-free rule recovers a
        // large fraction of ClusterWeighted's Δgini.
        let report = run_lottery_selection_sweep();
        let cw = report
            .redist_rows
            .iter()
            .find(|r| r.rule == Rule::ClusterWeighted)
            .unwrap();
        let fi = report
            .redist_rows
            .iter()
            .find(|r| r.rule == Rule::FeeInverse)
            .unwrap();
        assert!(
            cw.delta_gini > 0.0,
            "CW must reduce Gini: {}",
            cw.delta_gini
        );
        assert!(
            fi.delta_gini > 0.0,
            "FeeInverse must reduce Gini: {}",
            fi.delta_gini
        );
        // FeeInverse should recover a substantial share (not a full match).
        assert!(
            fi.recovery_pct > 40.0,
            "FeeInverse should recover a meaningful share of CW, got {:.1}%",
            fi.recovery_pct
        );
    }

    #[test]
    fn ct_flags_are_correct() {
        assert!(!Rule::ClusterWeighted.is_ct_clean());
        for rule in [
            Rule::Uniform,
            Rule::FeeInverse,
            Rule::CirculationGated,
            Rule::Hybrid,
        ] {
            assert!(rule.is_ct_clean(), "{} should be CT-clean", rule.label());
        }
    }

    #[test]
    fn report_is_reproducible() {
        let a = to_markdown(&run_lottery_selection_sweep());
        let b = to_markdown(&run_lottery_selection_sweep());
        assert_eq!(a, b, "sweep output must be byte-for-byte deterministic");
    }

    #[test]
    fn markdown_has_all_sections() {
        let md = to_markdown(&run_lottery_selection_sweep());
        assert!(md.contains("Track 1 — redistribution"));
        assert!(md.contains("Track 2 — Sybil resistance"));
        assert!(md.contains("CT-compatibility"));
        for rule in Rule::all() {
            assert!(md.contains(rule.label()), "missing rule {}", rule.label());
        }
    }
}
