// Copyright (c) 2024 The Botho Foundation

//! Coverage-gap unit tests for configuration parsing and chain address
//! types (#828). Kept in a dedicated file (rather than the per-module
//! `mod tests`) so concurrent test work on the same modules does not
//! conflict.

use crate::{
    BridgeConfig, BthConfig, Chain, ChainAddress, EthereumConfig, GasPriceStrategy,
    SolanaCommitment, SolanaConfig,
};

/// A complete, representative TOML document exercising every section —
/// nothing else in the suite parses a FULL config file.
const FULL_CONFIG_TOML: &str = r#"
[bth]
rpc_url = "http://localhost:7101"
ws_url = "ws://localhost:7101/ws"
view_key_file = "keys/view.enc"
confirmations_required = 2
reserve_address = "bth_reserve_addr"
release_signers = ["aa11", "bb22"]
release_threshold = 2
release_confirmations_required = 1

[ethereum]
rpc_url = "https://sepolia.example/rpc"
wbth_contract = "0x1111111111111111111111111111111111111111"
safe_address = "0x2222222222222222222222222222222222222222"
chain_id = 11155111
private_key_file = "keys/relayer.hex"
confirmations_required = 6
mint_signers = [
    "0x3333333333333333333333333333333333333333",
    "0x4444444444444444444444444444444444444444",
]
mint_threshold = 2

[ethereum.gas_price_strategy]
fixed = 30

[solana]
rpc_url = "https://api.devnet.solana.com"
wbth_program = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
commitment = "confirmed"
mint_signers = ["cc33"]
mint_threshold = 1

[bridge]
mnemonic_file = "bridge_mnemonic.enc"
db_path = "bridge.db"
fee_bps = 25
min_fee = 500000000
testnet = true

[reserve]
tolerance_picocredits = 0
reconcile_interval_secs = 30
"#;

#[test]
fn test_full_config_document_parses() {
    let config: BridgeConfig = toml::from_str(FULL_CONFIG_TOML).unwrap();

    assert_eq!(config.bth.confirmations_required, 2);
    assert_eq!(
        config.bth.reserve_address.as_deref(),
        Some("bth_reserve_addr")
    );
    assert_eq!(config.bth.release_threshold, 2);
    assert!(config.bth.spend_key_file.is_none());

    assert_eq!(config.ethereum.chain_id, 11155111);
    assert_eq!(
        config.ethereum.safe_address.as_deref(),
        Some("0x2222222222222222222222222222222222222222")
    );
    assert_eq!(config.ethereum.mint_signers.len(), 2);
    assert_eq!(config.ethereum.mint_threshold, 2);
    assert!(matches!(
        config.ethereum.gas_price_strategy,
        GasPriceStrategy::Fixed(30)
    ));

    assert!(matches!(
        config.solana.commitment,
        SolanaCommitment::Confirmed
    ));
    assert_eq!(config.solana.mint_threshold, 1);

    assert_eq!(config.bridge.fee_bps, 25);
    assert_eq!(config.bridge.min_fee, 500_000_000);
    assert!(config.bridge.testnet);
    // Unspecified knobs fall back to defaults.
    assert_eq!(config.bridge.max_retries, 3);
    assert!(!config.bridge.paused);

    assert_eq!(config.reserve.reconcile_interval_secs, 30);
}

#[test]
fn test_config_from_file_happy_and_error_paths() {
    // Happy path: a real file on disk round-trips through from_file.
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("bridge.toml");
    std::fs::write(&path, FULL_CONFIG_TOML).unwrap();
    let config = BridgeConfig::from_file(path.to_str().unwrap()).unwrap();
    assert_eq!(config.ethereum.chain_id, 11155111);

    // Missing file: readable error, no panic.
    let missing = BridgeConfig::from_file(dir.path().join("nope.toml").to_str().unwrap());
    assert!(missing.unwrap_err().contains("Failed to read config"));

    // Malformed TOML: parse error, no panic.
    let bad_path = dir.path().join("bad.toml");
    std::fs::write(&bad_path, "this is [not toml").unwrap();
    let bad = BridgeConfig::from_file(bad_path.to_str().unwrap());
    assert!(bad.unwrap_err().contains("Failed to parse config"));
}

#[test]
fn test_default_config_round_trips_through_toml() {
    // Every field of the default config serializes and parses back — a
    // config file generated by tooling from the defaults stays loadable.
    let config = BridgeConfig::default();
    let serialized = toml::to_string(&config).unwrap();
    let reparsed: BridgeConfig = toml::from_str(&serialized).unwrap();

    assert_eq!(reparsed.bridge.fee_bps, config.bridge.fee_bps);
    assert_eq!(reparsed.ethereum.chain_id, config.ethereum.chain_id);
    assert_eq!(
        reparsed.reserve.reconcile_interval_secs,
        config.reserve.reconcile_interval_secs
    );
    assert!(matches!(
        reparsed.ethereum.gas_price_strategy,
        GasPriceStrategy::Medium
    ));
    assert!(matches!(
        reparsed.solana.commitment,
        SolanaCommitment::Finalized
    ));
}

#[test]
fn test_gas_price_strategy_variants_parse() {
    #[derive(serde::Deserialize)]
    struct Wrap {
        gps: GasPriceStrategy,
    }

    let low: Wrap = toml::from_str(r#"gps = "low""#).unwrap();
    assert!(matches!(low.gps, GasPriceStrategy::Low));
    let medium: Wrap = toml::from_str(r#"gps = "medium""#).unwrap();
    assert!(matches!(medium.gps, GasPriceStrategy::Medium));
    let high: Wrap = toml::from_str(r#"gps = "high""#).unwrap();
    assert!(matches!(high.gps, GasPriceStrategy::High));
    let fixed: Wrap = toml::from_str("gps = { fixed = 42 }").unwrap();
    assert!(matches!(fixed.gps, GasPriceStrategy::Fixed(42)));

    // Unknown strategy is a config error, not a silent default.
    assert!(toml::from_str::<Wrap>(r#"gps = "warp""#).is_err());
}

#[test]
fn test_solana_commitment_variants_parse() {
    #[derive(serde::Deserialize)]
    struct Wrap {
        c: SolanaCommitment,
    }

    let processed: Wrap = toml::from_str(r#"c = "processed""#).unwrap();
    assert!(matches!(processed.c, SolanaCommitment::Processed));
    let confirmed: Wrap = toml::from_str(r#"c = "confirmed""#).unwrap();
    assert!(matches!(confirmed.c, SolanaCommitment::Confirmed));
    let finalized: Wrap = toml::from_str(r#"c = "finalized""#).unwrap();
    assert!(matches!(finalized.c, SolanaCommitment::Finalized));
    assert!(toml::from_str::<Wrap>(r#"c = "instant""#).is_err());
}

#[test]
fn test_ethereum_federation_knobs_default_and_parse() {
    // A pre-federation config still parses with fail-safe defaults
    // (empty signer set, zero threshold => dev-stub attestation only).
    let legacy: EthereumConfig = toml::from_str(
        r#"
        rpc_url = "http://localhost:8545"
        wbth_contract = "0x0000000000000000000000000000000000000000"
        chain_id = 1
        "#,
    )
    .unwrap();
    assert!(legacy.mint_signers.is_empty());
    assert_eq!(legacy.mint_threshold, 0);
    assert!(legacy.safe_address.is_none());
    assert_eq!(legacy.confirmations_required, 12, "default depth");

    // Solana federation knobs default the same way.
    let sol_legacy: SolanaConfig = toml::from_str(
        r#"
        rpc_url = "http://localhost:8899"
        wbth_program = "11111111111111111111111111111111"
        "#,
    )
    .unwrap();
    assert!(sol_legacy.mint_signers.is_empty());
    assert_eq!(sol_legacy.mint_threshold, 0);
}

#[test]
fn test_bth_config_requires_urls() {
    // rpc_url / ws_url have no defaults: omitting them is a parse error
    // (fail-closed), not a silently-wrong localhost fallback.
    assert!(toml::from_str::<BthConfig>("").is_err());
    assert!(toml::from_str::<BthConfig>(r#"rpc_url = "http://x""#).is_err());
}

#[test]
fn test_fee_calculation_no_overflow_and_extremes() {
    let mut config = BridgeConfig::default();

    // u64::MAX amount must not overflow (fee math widens through u128).
    config.bridge.fee_bps = 10_000; // 100%
    assert_eq!(config.calculate_fee(u64::MAX), u64::MAX);

    // 100% fee of a normal amount is the amount itself.
    assert_eq!(config.calculate_fee(5_000_000_000_000), 5_000_000_000_000);

    // 0 bps floors at the configured minimum fee.
    config.bridge.fee_bps = 0;
    assert_eq!(config.calculate_fee(u64::MAX), config.bridge.min_fee);

    // Fee on a zero amount is still the minimum (orders below the minimum
    // fee are not economically expressible).
    assert_eq!(config.calculate_fee(0), config.bridge.min_fee);
}

// ---------------------------------------------------------------------------
// Chain / ChainAddress coverage
// ---------------------------------------------------------------------------

#[test]
fn test_chain_from_str_case_insensitive_and_unknown() {
    assert_eq!("BTH".parse::<Chain>().unwrap(), Chain::Bth);
    assert_eq!("Botho".parse::<Chain>().unwrap(), Chain::Bth);
    assert_eq!("ETHEREUM".parse::<Chain>().unwrap(), Chain::Ethereum);
    assert_eq!("Sol".parse::<Chain>().unwrap(), Chain::Solana);

    let err = "dogecoin".parse::<Chain>().unwrap_err();
    assert!(err.contains("Unknown chain"));
    assert!("".parse::<Chain>().is_err());
}

#[test]
fn test_chain_display_round_trips_through_from_str() {
    for chain in [Chain::Bth, Chain::Ethereum, Chain::Solana] {
        let round = chain.to_string().parse::<Chain>().unwrap();
        assert_eq!(round, chain);
    }
}

#[test]
fn test_chain_serde_lowercase() {
    // The wire format is lowercase (DB rows, API payloads, attestation
    // envelopes all rely on it).
    assert_eq!(
        serde_json::to_string(&Chain::Ethereum).unwrap(),
        r#""ethereum""#
    );
    assert_eq!(serde_json::to_string(&Chain::Bth).unwrap(), r#""bth""#);
    assert_eq!(
        serde_json::from_str::<Chain>(r#""solana""#).unwrap(),
        Chain::Solana
    );
    assert!(serde_json::from_str::<Chain>(r#""Ethereum""#).is_err());
}

#[test]
fn test_eth_address_validation_rejects_non_hex() {
    // Correct length and prefix but a non-hex character.
    let bad = ChainAddress::new(
        Chain::Ethereum,
        "0x1234567890abcdef1234567890abcdef1234567g",
    );
    assert!(bad.validate().unwrap_err().contains("valid hex"));

    // Uppercase hex is accepted (checksummed addresses).
    let checksummed = ChainAddress::new(
        Chain::Ethereum,
        "0x52908400098527886E0F7030069857D2E4169EE7",
    );
    assert!(checksummed.validate().is_ok());
}

#[test]
fn test_solana_address_validation_bounds() {
    let valid = ChainAddress::new(
        Chain::Solana,
        "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
    );
    assert!(valid.validate().is_ok());

    let empty = ChainAddress::new(Chain::Solana, "");
    assert!(empty.validate().is_err());

    let too_short = ChainAddress::new(Chain::Solana, "abc");
    assert!(too_short.validate().unwrap_err().contains("32-44"));

    let too_long = ChainAddress::new(Chain::Solana, "x".repeat(45));
    assert!(too_long.validate().is_err());
}

#[test]
fn test_bth_address_validation() {
    let valid = ChainAddress::new(Chain::Bth, "bth_some_base58_address");
    assert!(valid.validate().is_ok());

    let empty = ChainAddress::new(Chain::Bth, "");
    assert!(empty.validate().unwrap_err().contains("empty"));
}

#[test]
fn test_chain_address_display_and_serde_round_trip() {
    let addr = ChainAddress::new(
        Chain::Ethereum,
        "0x1234567890abcdef1234567890abcdef12345678",
    );
    assert_eq!(
        addr.to_string(),
        "ethereum:0x1234567890abcdef1234567890abcdef12345678"
    );

    let json = serde_json::to_string(&addr).unwrap();
    let back: ChainAddress = serde_json::from_str(&json).unwrap();
    assert_eq!(back, addr);
}
