#!/usr/bin/env bash
# version.sh - Manage version across all botho-native packages.
# Generated by /loom:bump — safe to edit; subsequent /loom:bump runs reuse this script.
#
# Usage:
#   ./scripts/version.sh                  # Show current version
#   ./scripts/version.sh check            # Verify all files are in sync
#   ./scripts/version.sh bump patch       # X.Y.Z → X.Y.(Z+1)
#   ./scripts/version.sh bump minor       # X.Y.Z → X.(Y+1).0  (consensus-breaking in 0.x)
#   ./scripts/version.sh bump major       # X.Y.Z → (X+1).0.0
#   ./scripts/version.sh set 1.2.3        # Set explicit version
#   ./scripts/version.sh set 1.2.3 --tag  # Set + commit + tag
#
# Scope: this script manages the *botho-native* crates and npm packages only.
# The MobileCoin-fork crates that carry the upstream `7.1.0` version (under
# account-keys/, common/, consensus/, core/, crypto/{box,digestible,hashes,
# keys,multisig,ring-signature,sig}/, transaction/, util/) are deliberately
# EXCLUDED — they track the upstream fork point, not the botho release line.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# All files that contain the botho release version string.
# Order matters: the FIRST entry is the canonical source for `get_version`.
VERSION_FILES=(
  "botho/Cargo.toml"
  "botho-wallet/Cargo.toml"
  "botho-exchange-scanner/Cargo.toml"
  "bridge/core/Cargo.toml"
  "bridge/service/Cargo.toml"
  "cluster-tax/Cargo.toml"
  "crypto/pq/Cargo.toml"
  "crypto/secp256k1/Cargo.toml"
  "discover/Cargo.toml"
  "gossip/Cargo.toml"
  "infra/faucet/metrics-daemon/Cargo.toml"
  "mobile/rust-bridge/Cargo.toml"
  "web/packages/desktop/src-tauri/Cargo.toml"
  "web/package.json"
  "contracts/ethereum/package.json"
  "mobile/app/package.json"
)

get_version() {
  # Canonical source: botho/Cargo.toml ([package] version).
  grep -m1 '^version = "' "$REPO_ROOT/botho/Cargo.toml" | sed 's/version = "\(.*\)"/\1/'
}

get_version_from_file() {
  local file="$1"
  case "$file" in
    *.json)
      jq -r '.version' "$REPO_ROOT/$file"
      ;;
    *.toml)
      # Cargo: [package] version = "..."
      grep -m1 '^version' "$REPO_ROOT/$file" | sed 's/version = "\(.*\)"/\1/'
      ;;
  esac
}

check_versions() {
  local expected
  expected=$(get_version)
  local all_match=true

  for file in "${VERSION_FILES[@]}"; do
    local actual
    actual=$(get_version_from_file "$file")
    if [ "$actual" != "$expected" ]; then
      echo "MISMATCH  $file: $actual (expected $expected)"
      all_match=false
    else
      echo "OK        $file: $actual"
    fi
  done

  if $all_match; then
    echo ""
    echo "All versions in sync: $expected"
    return 0
  else
    echo ""
    echo "Version mismatch detected. Run: $0 set $expected"
    return 1
  fi
}

bump_version() {
  local current="$1"
  local part="$2"

  IFS='.' read -r major minor patch <<< "$current"

  case "$part" in
    major) echo "$((major + 1)).0.0" ;;
    minor) echo "$major.$((minor + 1)).0" ;;
    patch) echo "$major.$minor.$((patch + 1))" ;;
    *) echo "Unknown bump type: $part (use major, minor, or patch)" >&2; exit 1 ;;
  esac
}

set_version() {
  local new_version="$1"

  if ! [[ "$new_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid version format: $new_version (expected X.Y.Z)" >&2
    exit 1
  fi

  local old_version
  old_version=$(get_version)

  echo "Updating version: $old_version → $new_version"
  echo ""

  # Cargo.toml writers (rewrite the FIRST `version = "..."` line — that's the
  # `[package]` version; any `version = "..."` lines under `[dependencies]`
  # are followed by other keys (`path`, `features`) and are not the leading
  # `version` key of their table).
  for file in "${VERSION_FILES[@]}"; do
    case "$file" in
      *.toml)
        awk -v ver="$new_version" '!done && /^version = "/ { print "version = \"" ver "\""; done=1; next } 1' \
          "$REPO_ROOT/$file" > "$REPO_ROOT/$file.tmp" && mv "$REPO_ROOT/$file.tmp" "$REPO_ROOT/$file"
        echo "  Updated $file"
        ;;
      *.json)
        local tmp
        tmp=$(mktemp)
        jq --arg v "$new_version" '.version = $v' "$REPO_ROOT/$file" > "$tmp"
        mv "$tmp" "$REPO_ROOT/$file"
        echo "  Updated $file"
        ;;
    esac
  done

  # Refresh Cargo.lock so the workspace crate versions in it match.
  # `cargo update -w` updates only workspace members; the registry
  # dependency graph is left alone.
  if [ -f "$REPO_ROOT/Cargo.lock" ]; then
    (cd "$REPO_ROOT" && cargo update -w 2>/dev/null) && echo "  Updated Cargo.lock"
  fi

  echo ""
  echo "Version set to $new_version"
}

do_tag() {
  local version="$1"

  echo ""
  echo "Committing and tagging..."
  (
    cd "$REPO_ROOT"
    git add "${VERSION_FILES[@]}"
    [ -f "Cargo.lock" ] && git add Cargo.lock
    [ -f "CHANGELOG.md" ] && git add CHANGELOG.md
    git commit -m "chore: bump version to $version"
    git tag -a "v$version" -m "v$version"
  )
  echo ""
  echo "Created commit and tag v$version"
  echo "Push with: git push origin HEAD --tags"
}

# --- Main ---

case "${1:-}" in
  ""|show)
    echo "$(get_version)"
    ;;
  check)
    check_versions
    ;;
  bump)
    part="${2:-patch}"
    current=$(get_version)
    new_version=$(bump_version "$current" "$part")
    set_version "$new_version"
    if [ "${3:-}" = "--tag" ]; then
      do_tag "$new_version"
    fi
    ;;
  set)
    if [ -z "${2:-}" ]; then
      echo "Usage: $0 set <version> [--tag]" >&2
      exit 1
    fi
    set_version "$2"
    if [ "${3:-}" = "--tag" ]; then
      do_tag "$2"
    fi
    ;;
  *)
    echo "Usage: $0 [show|check|bump <major|minor|patch> [--tag]|set <version> [--tag]]"
    exit 1
    ;;
esac
