/**
 * Address-format-v2 codec parity (TS `@botho/core` ⇄ Rust shared codec / node).
 *
 * `@botho/core`'s `formatAddress` / `parseAddress` encode and decode the v2
 * base58 body `view(32)‖spend(32)‖kem(1184)‖dsa(1952)`. That layout MUST be
 * byte-identical to the shared Rust `address-codec` (and therefore to every
 * botho://2/ address the node emits), or a browser-parsed recipient key or a
 * displayed address would drift from the chain.
 *
 * The golden below is produced by the Rust side for the canonical BIP39 test
 * mnemonic ("abandon…about"): both the wasm-signer's `derive_address_from_seed`
 * unit test and the node's own `WalletKeys::public_address_string` emit exactly
 * this string (verified in this PR). Decoding it here with `parseAddress` and
 * recovering the same classical keys proves the TS codec agrees with the node.
 */

import { describe, it, expect } from 'vitest'
import { parseAddress, formatAddress, isValidAddress } from './address'

// GOLDEN: the testnet v2 address the node derives for the canonical BIP39
// "abandon abandon … about" mnemonic. Generated by the Rust
// `bth-wasm-signer` unit test `v2_address_from_seed_matches_node_derivation`
// and cross-checked against `botho-wallet`'s `WalletKeys::public_address_string`.
const GOLDEN_TESTNET_ADDRESS =
  'tbotho://2/apm8kqabmyjn7V6R35S7ZN2bAYoupZGbqQX4u5H62LRih6vDZu2ZvAAJXiUSXN6amQPusu9gEGwWwP22fdeJeU4PZ5ikmjKB8FfgeQjEEBnqr117z2pxXo96jLEH2Q7HjxFWkHLCTzLKmkHhQPL2c5uSCAxzrSXRZkdvGsFfy7kkC2YR5121SgghjSFzX3ThA2Jf6xU9ZMwHxDJbHHA7GhytiB7197BNNhicsTQ26GAUDEAikKPFV2pkWUqnXHF7zX9fRfvTURUZqrGeWskvYCKTngN753rJtjMWwoqCVs2MmaJAnrfTb56rpwNHZiQgbhF7S4zFVYXYwUUSs1uJYCZrUZ2qJeZC4USMX9MCkzJbuizJHeNoWVKfe1eqdkLiX9TQBU1W44QdnNM6N65ve157hDe6ATUD4K8FiqARLz8VgMRvj1Ai4xYDaJGo38oC1d2dSunNwkUYMr6ucFyF2fv4WtAXgNUaDxsFT8Hpxqd4mTGjBKA7dBNtWQfn1zAQHqKZpehaPE3eHP3MujYi62iHme1JkcRpbwjAuLPXWRrD8WBbzVctrsMbnRwVE8uttAbX3CHRwVHBDodUWGXyRGib1wocMLW3WrnRGXdnnEtD7PzLK2rJ25zdm8ZTyMSE1aEPpp5W7HKLv8iFkWhitCDasUagv7VGkNjizp26rFpm3osimjUapAVSY1ShrAXeqbw5PWH3nS5KXmUtPivB1FNifGcTm3Soiziq4twPqBKmMey3vTU6edULkZB1wiXWEeFmJ3uziqFKfitzjYYsgbk5mgTetzTgx13WrAhwfJK5rFkU3ZGKPVEdg6ARB94UGXZWScNdi8S1fspJoaTvDydMmFrgvsGHYVpFfNyjYwU7uD9aVfVHsEwwoPQt9KNGoZbUxLBJ5VzbkaRaers8zRtU25yx8Qakr5oTZFwbA4xnGtuSCXqaEiu2dNnha6RXSvJ5J8XsnGydCvvqW1UfkjdpNVGbgPDh1Vc77T46zDE1VaTGjKxwBoiqMz6YaUF61nCXXcJL3QeDDs8HZH6DBeD6HEwHQoCJRNZ9VGNiFx3699yziLuJXHECTRbwpdqy3ybhWrjL43xTPJnJRXY62ye3XpWPUH4Wmyns8WYzBS3T6ay9Xyf4zrFTC8MUYyCMUfPFqwak1jZ7uh7JYvGuLGcd1TjV3sgngmy5nx349rQAZXUhapTFF5QtdePXPunQxK6QzvGqk7Aeuxtr317NxT77M1AMHC3N9zbMtjaKypUW5RrkJfuTA3S2h45Cz4n74fbmrRc54TktsonGkMzNTTkQre79sQRZXgQtXYNghrPyNzEmo8CTwUMkThw3fkkPfVppaw9VPZpoqonQLG8SCNmwj9YteUM5BYWKQvoRMXy4kBW95jMCPXXkXjkjFLC1qpCiRjXUZd6wd64u2sXKfLJ9fMgz54NknAuYiZawUZLWWkehkdfgwpeXgWd48FL6ZmV2xBZmA3s8JGPiYbAqRYwNySKsKNaDNd7rsh4xbKb2QR6vVuBkgrryVgAKeTymf8hEAE3tpq9puKhu1jGp4q61n6SUyWsXka8ekrjyJVFNXXPF6XpFGC6D5wY8n9kzVgq6kupxZAep4qyFHtudFcqRzNwm1eqeFoRxuCZhyyFFynGJTMWgLBTQ1oQQSX7gD3h2bFFGxtcZp8EEdFZG4faZwXgw79qz1Ft5N2FwfGKwjBcjWVAdVH85Fm7piKdoMSnfwBAqfLPhPQd31qvNZ7F4abRcMTUhjMPDoWD5g8TbDSnQcj9fcw8uE4s7C59xufYibpKxBP4o52pe8pWaNsCrjC6xG2Ss7ZZuU8z2X9sVxkaw37opneLkbwd9CMLLvEYFzQJMv32DM66m6HnKgijtwgUBbyrgYwwc7UzPVteG4VCjMnoeQbAWPNEVDZmnQ5k2HtpEa6K1jvKUS2zT3gxoktmBD17d9a9GzwjMB8jDBn9vRqTogzaJLXyNBbAkTmrZWJoVDNSqEYZQntX3RsCnTVdauCXnFx11NTpZ9tFoKeoQs9r7N6u1ur2Rg5mhRoGUy6iCm4Ndfj4ukNXh1heSUf4cTHDeHTCeeSQbquYNYR7VtagLnGEogA2neETexLzuYtDpE5UsCmJW6JD3tXmL5vtwUJgiwzgHoRUgCyFTQcX5sRax27AWewwmzWUBH1A374S3CogyunE6Ar1Mdoq98rgtNZyctjXXkBxfrF2wQ7rV4dTpAWx8vNVzdMLvQYqipkdWRG7NKrLtfe2VndZvULuQpDJT1QcjqXFb65DeEhbsJGZQ2GyqBNnKDPCNA8ToHYJG3UgePqqT5vZqz4eo29heS1i1raFmeadkFss2HtY6PToVXPJGcJRT9dSHPHD4Mab4TcfziydCgPiWEVQMbxdVV34K8K81gEjjMFr3bs66beHMgB54mCm4pd9rYQaQY63bfHT1Hk6nzD2TvAsVCW6hCcpja5vYxMTy1BJ1LXqfvrysvwDsTKHcqK1eicoJhqiCV48PeLthsdfPDNJP3ynsQvYoN66RVZHSRN7K63u75ZANiMDCFSZN7M4c5WyoLTyWHcB7Q2F93c2HEHBjNuuJQHmhXt3sHccG36ejcZtzcnBcmRSSZ5bHNEDo2oJuuiyRQnCEQ29CCwoGwunxNijkuD75rDdiBUedKZjyaqjAS4sZJZeHe6NCMEDzh4qgTUDUmjgZz1dyx7S45RHsdB7CEbnyiDeBYEinwTtEqQbPKJY6FJwQ4ctbovNTGZBRdhLFQD5DwEHHk7Fmmm3pfXF8cZB9qhTFYstVBJaGUfUGLHwGuzqH8qeEJ8sec9F4JZAr3DrVY42krBBJDiMPru866tZkqjGvzQLP8xQz2XcgcvDwWuEsbF34bTFi5HzfreycywGoLfcN2L69FEny4knrbSpNCmn8qXcV1k5qq6WkLwr9SneY2BEKZxd29Ug5fpbtGoT3jjxbVccNuEhQDqJ2TxQzEgXTPBFZbgYMVo8HxFrqGczMwwZMDTeMRMGS7Br8rsmU45zk1rR22aWho1yTTwD2WGhpcPuxvqjWfy93gvmEoRS1nT8MvDvCktRkXwCtoCoRz4ZQwE5L3JzhtFzh3Vmo8Gnqj7jqxHKDmCfjPqd4DZrySucCcKYs1yr4Nk59T8DSzmZ7J2HdnRUPuD3yLt2tMVNDVESaNkviyVmCdb2R5N67XKfhDAxp3v3UzF1sbFHLYH7tgfKQw6rtiCT7g4ZHGafawwZDZb1dgJByDkCaSjdaiKCB7aQMKmjq9g6gAMcwD1pbGz9FvbhWL25n6J7m2DhLDCo5fnQR4FVqaNoB5trVc2wv2X96RcWzZp4QQPAum7p7CBk6kwRqr8sGdvh3ko55WvYTZG3oDjAd3VfScRTFMo3BTTrNgVJpwAdWZsnikL2ewKyLDjHxKPnB5EB3iGbKXrjkrgPMJ3M7spB3T3HqVafXmgfyKmwuPhvEUNn77mr4X8dsDMGnLB3vaeQRZP1RSAWFgZusDFKvYY8JwFcEBswUb5JgjSNvUSU2T5pFcc8mqTB53nAzCNoHvX5FBnQCXrWpN3E359PBiiuJmeBdQhjWh7yCh3NzdxNhKcsySgiNDUXkQSnGirmPMMiwKrXRrv6XXFyyxsdBErWGKzc2cDqYbzygiyBYeYk8SB9cJioJ6S4DRbZs7NxY2jsNK9JUPGDeUeVuDNdVwSuBucwDhjeCBtSzUCQy8ET6Lyu6SduG6cF9xb6JC693nsgx7VENQApY3Bc8bLkKDXz8JYuSXnQbSouXLgperYLQS3rjd3ZLUmKYyW3pr75R79ZEwftqtNQzRaPNAohCBJaCvA2BdG8SPaWbJZ6UdSxLzm3tJ1uYC2kaHhzub4jmnYAGuCVHLBwbppShmsVKxnfUyo2L8fDguzPc2kr6CBjcsxLgBaAUiE9tk2S6DDngBZ3f3UNdrv4yy5dp2p1nWHN9FRtVgybRvCYvdm8wspsRWH23muUN2FrGgFV5WTeigrgoQ8DRZpn7zpLYwMvwzbtZFWHcN5b9xFbNnzh27A3X5eGuvF1tbUXA21Rk2Ey9myfdSrDxpxFkFWNbdxpVLoSdDKLu5Frq9yrvxafjwP3DvBCZsvZ4gpDva7qSGaEEXnuDPycPWBgUpwYpDs1vPdBAef1U3EvznqZ6HTgG9C8znD47E9MURoaxwwxZq448cEdHtor9Rdz7iCHTrsJW9PxyVB9cnsze1tdYPzBMwvd1tts8r27nzWegNhUpDr8D2E8qBqkPLU4UZzfz1gL5roGdNyt5dQSeig1JsBU62imeYQ753eNCbiLW8uvcKyJKCBwoYVVB46UAoc3nfAGa1vfboZYBNp9AovLsqvn5JxiNxu2cLNNSA9'

// Classical default-subaddress keys the node derives for that mnemonic
// (also asserted by `derivation-parity.test.ts`).
const EXPECTED_VIEW_HEX = '60eeebc23d5d4fa3b90621292da88f39c6df05114bd405319cf9adc905905773'
const EXPECTED_SPEND_HEX = '8e2cf7239559d62c6ca0c0718eac345da1fa9348aa741a94d6489025a05a917c'

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

describe('address v2 codec parity (TS <-> Rust/node)', () => {
  it('decodes the node golden into the right components', () => {
    const parsed = parseAddress(GOLDEN_TESTNET_ADDRESS)
    expect(parsed.network).toBe('testnet')
    expect(toHex(parsed.viewPublic)).toBe(EXPECTED_VIEW_HEX)
    expect(toHex(parsed.spendPublic)).toBe(EXPECTED_SPEND_HEX)
    expect(parsed.kemPublic).toHaveLength(1184)
    expect(parsed.dsaPublic).toHaveLength(1952)
  })

  it('re-encodes the decoded golden to the identical string (round-trip)', () => {
    const parsed = parseAddress(GOLDEN_TESTNET_ADDRESS)
    const reencoded = formatAddress(
      parsed.viewPublic,
      parsed.spendPublic,
      parsed.kemPublic,
      parsed.dsaPublic,
      'testnet',
    )
    expect(reencoded).toBe(GOLDEN_TESTNET_ADDRESS)
  })

  it('accepts the golden as a valid address', () => {
    expect(isValidAddress(GOLDEN_TESTNET_ADDRESS)).toBe(true)
  })

  it('mainnet uses the same body under a different prefix', () => {
    const parsed = parseAddress(GOLDEN_TESTNET_ADDRESS)
    const mainnet = formatAddress(
      parsed.viewPublic,
      parsed.spendPublic,
      parsed.kemPublic,
      parsed.dsaPublic,
      'mainnet',
    )
    expect(mainnet.startsWith('botho://2/')).toBe(true)
    expect(mainnet.slice('botho://2/'.length)).toBe(
      GOLDEN_TESTNET_ADDRESS.slice('tbotho://2/'.length),
    )
  })

  it('rejects retired v1 and quantum prefixes loudly', () => {
    expect(() => parseAddress('botho://1/abc')).toThrow(/v1/)
    expect(() => parseAddress('tbotho://1/abc')).toThrow(/v1/)
    expect(() => parseAddress('botho://1q/abc')).toThrow(/[Qq]uantum/)
    expect(() => parseAddress('botho-pq://1/abc')).toThrow(/[Qq]uantum/)
  })
})
