/**
 * Build the EC2 user-data that boots a managed node via the P6.1 bootstrap
 * (`infra/baas/node-bootstrap.sh`, merged #499/#521).
 *
 * The bootstrap script reads its parameters from environment variables exported
 * before it runs (see its PARAMETERS header). cloud-init runs user-data as root
 * on first boot. We emit a small shell preamble that:
 *   1. exports NODE_ID / REGION / TIER (+ optional binary URL/sha) the bootstrap
 *      expects, and
 *   2. fetches and runs the bootstrap script.
 *
 * The script body itself is NOT inlined here (it lives in infra and is fetched
 * at boot from a pinned URL) to keep user-data small and the script
 * single-sourced. The provisioner supplies `BOOTSTRAP_SCRIPT_URL`.
 *
 * This module is pure — it returns the base64 user-data string and performs no
 * I/O — so it is fully unit-testable.
 */

export interface UserDataParams {
  /** Short opaque node id -> NODE_ID (derives node-<id>.<domain> in the script). */
  nodeId: string
  /** AWS region -> REGION (informational in the script; recorded in node-info). */
  region: string
  /** Instance type -> TIER (informational; MVP is t4g.medium). */
  tier: string
  /** Zone for the hostname -> NODE_DOMAIN. */
  nodeDomain: string
  /** Prebuilt linux-aarch64 botho binary URL -> BOTHO_BINARY_URL. */
  binaryUrl?: string
  /** sha256 to pin the binary -> BOTHO_BINARY_SHA256. */
  binarySha256?: string
  /**
   * URL of the node-bootstrap.sh script to fetch + run. Defaults to the published
   * location under the testnet domain; overridable per-environment.
   */
  bootstrapScriptUrl?: string
}

const DEFAULT_BOOTSTRAP_SCRIPT_URL =
  'https://raw.githubusercontent.com/botho-project/botho/main/infra/baas/node-bootstrap.sh'

/** Shell-quote a value for safe `export KEY='value'`. */
function shQuote(value: string): string {
  // Wrap in single quotes; escape embedded single quotes the POSIX way.
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/**
 * Render the cloud-init user-data shell script (plain text). Exported separately
 * so tests can assert on the human-readable script before base64.
 */
export function renderUserDataScript(params: UserDataParams): string {
  const scriptUrl = params.bootstrapScriptUrl ?? DEFAULT_BOOTSTRAP_SCRIPT_URL
  const lines: string[] = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '# Botho managed-node bootstrap (generated by the BaaS provisioner, #502).',
    `export NODE_ID=${shQuote(params.nodeId)}`,
    `export NODE_DOMAIN=${shQuote(params.nodeDomain)}`,
    `export REGION=${shQuote(params.region)}`,
    `export TIER=${shQuote(params.tier)}`,
    'export NETWORK=testnet',
  ]
  if (params.binaryUrl) {
    lines.push(`export BOTHO_BINARY_URL=${shQuote(params.binaryUrl)}`)
  }
  if (params.binarySha256) {
    lines.push(`export BOTHO_BINARY_SHA256=${shQuote(params.binarySha256)}`)
  }
  lines.push(
    `BOOTSTRAP_URL=${shQuote(scriptUrl)}`,
    'curl -fsSL "$BOOTSTRAP_URL" -o /root/node-bootstrap.sh',
    'chmod +x /root/node-bootstrap.sh',
    'exec /root/node-bootstrap.sh',
    '',
  )
  return lines.join('\n')
}

/**
 * Build base64-encoded user-data for EC2 RunInstances. `encode` is injected so
 * the same code runs in the Worker (btoa-based) and in tests (deterministic).
 */
export function buildUserData(
  params: UserDataParams,
  encode: (s: string) => string,
): string {
  return encode(renderUserDataScript(params))
}
