#!/usr/bin/env bash
#
# Setup automated backup for Botho seed node
#
# This script:
#   1. Installs required dependencies
#   2. Configures S3 bucket with lifecycle policy
#   3. Installs and enables systemd timer
#
# Prerequisites:
#   - AWS CLI configured
#   - sudo access
#
# Usage:
#   sudo ./setup-backup.sh <s3-bucket-name> [region]
#
# Example:
#   sudo ./setup-backup.sh my-botho-backups us-east-1

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Validate arguments
if [[ $# -lt 1 ]]; then
    echo "Usage: sudo $0 <s3-bucket-name> [region]"
    echo ""
    echo "Arguments:"
    echo "  s3-bucket-name  S3 bucket for backups (will be created if doesn't exist)"
    echo "  region          AWS region (default: us-east-1)"
    exit 1
fi

# Check for root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

S3_BUCKET="$1"
AWS_REGION="${2:-us-east-1}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log_info "Setting up Botho ledger backup"
log_info "S3 Bucket: $S3_BUCKET"
log_info "Region: $AWS_REGION"

# Step 1: Install dependencies
log_info "Installing dependencies..."
if command -v apt &> /dev/null; then
    apt update
    apt install -y zstd lmdb-utils
elif command -v yum &> /dev/null; then
    yum install -y zstd lmdb
elif command -v dnf &> /dev/null; then
    dnf install -y zstd lmdb
else
    log_warn "Unknown package manager. Please install zstd and lmdb-utils manually."
fi

# Step 2: Create S3 bucket if needed
log_info "Checking S3 bucket..."
if ! aws s3api head-bucket --bucket "$S3_BUCKET" --region "$AWS_REGION" 2>/dev/null; then
    log_info "Creating S3 bucket: $S3_BUCKET"
    aws s3api create-bucket \
        --bucket "$S3_BUCKET" \
        --region "$AWS_REGION" \
        --create-bucket-configuration LocationConstraint="$AWS_REGION" \
        2>/dev/null || aws s3api create-bucket --bucket "$S3_BUCKET" --region "$AWS_REGION"

    # Enable versioning for extra protection
    aws s3api put-bucket-versioning \
        --bucket "$S3_BUCKET" \
        --region "$AWS_REGION" \
        --versioning-configuration Status=Enabled
fi

# Step 3: Configure bucket encryption
log_info "Configuring bucket encryption..."
aws s3api put-bucket-encryption \
    --bucket "$S3_BUCKET" \
    --region "$AWS_REGION" \
    --server-side-encryption-configuration '{
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "AES256"
                },
                "BucketKeyEnabled": true
            }
        ]
    }'

# Step 4: Configure lifecycle policy (30-day retention)
log_info "Configuring 30-day retention policy..."
aws s3api put-bucket-lifecycle-configuration \
    --bucket "$S3_BUCKET" \
    --region "$AWS_REGION" \
    --lifecycle-configuration '{
        "Rules": [
            {
                "ID": "DeleteOldBackups",
                "Status": "Enabled",
                "Filter": {
                    "Prefix": "ledger-backups/"
                },
                "Expiration": {
                    "Days": 30
                },
                "NoncurrentVersionExpiration": {
                    "NoncurrentDays": 7
                }
            }
        ]
    }'

# Step 5: Block public access
log_info "Blocking public access..."
aws s3api put-public-access-block \
    --bucket "$S3_BUCKET" \
    --region "$AWS_REGION" \
    --public-access-block-configuration '{
        "BlockPublicAcls": true,
        "IgnorePublicAcls": true,
        "BlockPublicPolicy": true,
        "RestrictPublicBuckets": true
    }'

# Step 6: Create configuration directory
log_info "Creating configuration..."
mkdir -p /etc/botho
cat > /etc/botho/backup.env << EOF
# Botho Seed Node Backup Configuration
# Generated by setup-backup.sh on $(date -Iseconds)

BOTHO_BACKUP_BUCKET=$S3_BUCKET
BOTHO_BACKUP_PREFIX=ledger-backups
BOTHO_LEDGER_PATH=/var/lib/botho/ledger
AWS_REGION=$AWS_REGION
EOF
chmod 600 /etc/botho/backup.env

# Step 7: Install systemd units
log_info "Installing systemd units..."
cp "$SCRIPT_DIR/botho-backup.service" /etc/systemd/system/
cp "$SCRIPT_DIR/botho-backup.timer" /etc/systemd/system/

# Create symlink for backup script
mkdir -p /opt/botho/infra/backup
cp "$SCRIPT_DIR/backup-ledger.sh" /opt/botho/infra/backup/
chmod +x /opt/botho/infra/backup/backup-ledger.sh

# Step 8: Enable and start timer
log_info "Enabling systemd timer..."
systemctl daemon-reload
systemctl enable botho-backup.timer
systemctl start botho-backup.timer

# Step 9: Run initial backup
log_info "Running initial backup..."
systemctl start botho-backup.service || log_warn "Initial backup failed - check logs with: journalctl -u botho-backup"

log_info "=========================================="
log_info "Backup setup complete!"
log_info "=========================================="
echo ""
echo "Configuration:"
echo "  - S3 Bucket: $S3_BUCKET"
echo "  - Retention: 30 days"
echo "  - Schedule: Daily at 2:00 AM UTC"
echo "  - Config file: /etc/botho/backup.env"
echo ""
echo "Commands:"
echo "  - View timer status: systemctl status botho-backup.timer"
echo "  - View backup logs: journalctl -u botho-backup"
echo "  - Run manual backup: systemctl start botho-backup"
echo "  - Verify backup: /opt/botho/infra/backup/backup-ledger.sh --verify-only"
echo ""
echo "Next steps:"
echo "  1. Create CloudWatch alarms for monitoring:"
echo "     ./create-backup-alarms.sh <instance-id> <sns-topic-arn>"
echo "  2. Verify backup by checking S3:"
echo "     aws s3 ls s3://$S3_BUCKET/ledger-backups/"
